- client/components/AllProducts.js
- client/store/index.js
- client/store/product.js
- server/db/models/user.js
> fixed combinereducers

- README.md
- client/components/AllProducts.js
-updated README
-made an adjustment to line 13 of AllProducts component (testing for length of the array)
> updated readme and minor update to line 13 of AllProducts comp

- public/index.html
> changed site title

- client/app.js
- client/components/SingleProduct.js
- client/components/index.js
- client/routes.js
- client/store/product.js
- server/api/products.js
update route for single product page
> updated route for singleProduct page

- client/history.js
- script/seed.js
- server/db/models/Product.js
- edited product DB model 
- edited seed file
> edited seed file and product model

- client/components/AllProducts.js
Fixed syntax error (missing bracket) in AllProducts component
> fix: fixed a syntax error in AllProducts.js, missing bracket

- client/components/AllProducts.js
Imported Component so that the AllProducts component can `extend` it
> fix: AllProducts importing `Component` from react

- client/components/AllProducts.js
- client/components/CartForm.js
- client/components/CartList.js
- client/components/SingleProduct.js
- client/components/index.js
- client/components/navbar.js
- client/routes.js
- client/store/product.js
- public/style.css
Update the cart rendering page
> add: update the cart front end to hook up with reducer

- public/style.css
- server/api/cart.js
- server/api/index.js
- server/api/products.js
- server/index.js
-Added post route for updating the cart on `req.session`
> Cart backend

- server/api/cart.js
Edited the `/api/cart` post route to respond with the updated cart
> fix: send req.session.cart back to the client

- client/components/CartForm.js
- client/store/cart.js
- client/store/index.js
- client/store/product.js
> Fix: Make a cart reducer 

- server/api/cart.js
Tried to use `.catch` without a promise chain, this will not work
> fix: .catch not working

- client/components/AllProducts.js
- client/components/AuthForm.js
- client/components/CartForm.js
- client/components/CartList.js
- client/components/Payments.js
- client/components/SingleProduct.js
- client/components/navbar.js
- client/routes.js
- server/api/users.js
- server/db/db.js
> refac: formatted stuff because i am ocd

- server/api/cart.js
Added a get route to `/api/cart`
> Get cart route

- client/components/AllProducts.js
- client/components/CartForm.js
> resolve branch issue

- server/db/models/Category.js
- server/db/models/Product.js
- server/db/models/index.js
- server/db/models/user.js
-created a Category model
-associated it with the Product model
> Category model

- server/db/models/Category.js
- server/db/models/Order.js
- server/db/models/Product.js
- server/db/models/index.js
- server/db/models/user.js
-created Order model
-associations between Order and Product/User models
> Order model

- client/components/CartList.js
- client/components/Payments.js
- client/store/cart.js
fix: render checkout page and update the total price
> fix: render checkout page and update the total price

- server/db/models/index.js
-`belongsToMany` associations needed to be defined with a `through` table
> fix: many to many associations

- client/components/CartForm.js
- client/components/CartList.js
- client/components/Payments.js
- server/api/cart.js
- fix: update the backend route (cart) so that we can add the same item multiple times
- add: add quantities in req.session.product.quantity property to keep track of the number of the quantity of the same item in cart
> update the backend route to include quantity on cart

- client/components/CartList.js
- server/api/cart.js
> Product quantity adjustment

- client/components/AllProducts.js
- client/components/AuthForm.js
- client/components/CartList.js
- public/style.css
sign up page and sign in page layout page is styled
> Styling: Fixing layout, signup/signin style

- client/components/AuthForm.js
- client/components/navbar.js
-added semantic-ui styling to navbar
-also styled the submit button in `AuthForm` component
> Navbar styling

- package-lock.json
- package.json
- public/style.css
> background color changed

- client/components/AllProducts.js
- package-lock.json
- package.json
-fixed issue where we were calling `forEach` method on an object
> fix: updated forEach in AllProducts

- client/components/navbar.js
changed Links to MenuItem hrefs
> fix: removed nested Links, added hrefs to MenuItems instead

- script/seed.js
-Added categories to the seed file
> add: include example product category associations in seed file

- client/components/CartForm.js
- client/components/CartList.js
- client/store/cart.js
- server/api/cart.js
- server/api/stripe.js
-Updated api routes and the client store per code review comments
> fix: updated api routes and client store

- server/api/users.js
-Added the gatekeeper middleware that was discussed in code review to the user.js api route
> add: gatekeeper middleware to user route

- client/components/CartForm.js
- client/components/CartItem.js
- client/components/CartList.js
- client/components/Payments.js
- client/store/cart.js
- server/api/cart.js
- server/api/stripe.js
- server/db/models/Order.js
- server/db/models/Product.js
> fix: fix the update quantity and payment functionality for logged in users

- client/components/CartList.js
- client/store/cart.js
> Post cart error

- client/components/AuthForm.js
- client/components/Navbar.js
- client/routes.js
- public/index.html
-updated the name to WizBang
-changed the '/' route to direct to the AllProducts component
-removed the sign-up prompt on AuthForm
> Update name wizbang

- package.json
- test/api_specs/users.api.spec.js
- test/component_specs/navbar.spec.js
- test/db_specs/Product.spec.js
- test/redux_specs/cart.redux.spec.js
test: wrote tests for users/api, navbar/component, product/db and cart/redux
> Joshua test

- server/api/stripe.js
- test/api_specs/users.api.spec.js
- test/api_specs/wishlist.spec.js
- test/component_specs/ProductCard.spec.js
- test/component_specs/user-home.spec.js
- test/db_specs/Category.spec.js
- test/redux_specs/user.redux.spec.js
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
*Your PR Notes Here*
> tested files

- public/style.css
- script/seed.js
-Added a bunch of items for sale to the seed file
-Updated the .css file to flex-wrap
> add: added a bunch of items to the seed file

- client/components/Payments.js
- server/api/stripe.js
-our secret key is no longer public!!
> Fix stripe api key
